
version: '3.8'

services:
  # Web application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - frontend-network
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/conf.d:/etc/nginx/conf.d

  # Backend API
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=dronenglb
      - JWT_SECRET=replace_this_with_secure_random_string
      - ADMIN_EMAIL=info@drohnenvermessung-roofergaming.de
      - ADMIN_PASSWORD=change_this_secure_password
    restart: unless-stopped
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - frontend-network
      - backend-network

  # PostgreSQL database
  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dronenglb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - backend-network

  # Certbot service for SSL certificates
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email info@drohnenvermessung-roofergaming.de --agree-tos --no-eff-email -d example.com -d www.example.com
    depends_on:
      - app

networks:
  frontend-network:
  backend-network:

volumes:
  postgres-data:
