// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://afqzkvwyfoojuftlvrfq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFmcXprdnd5Zm9vanVmdGx2cmZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3MTkwNDAsImV4cCI6MjA1NzI5NTA0MH0._TIKKzrMBfHb5ib4uEKEYLxdVpZGtXMiU8K_ruL3bek";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);